### ISSUE TITLE
PHP-Error without effect

### ISSUE THREAD

**Issue by snduesel** [pluspol-interactive/templavoila#13]
Hi @opi99 

i get every page call this php-error, but without a effect in the frontend and backend.

`AH01071: Got error 'PHP message: https://www.my-domain.com/ - templavoila: Argument "$dV" must be of type array, "NULL" given\nPHP message: https://www.my-domain.com/ - templavoila: Argument "$dV" must be of type array, "NULL" given\nPHP message: https://www.my-domain.com/ - templavoila: Argument "$dV" must be of type array, "NULL" given\n'`

> PHP7 - TYPO3 7.6.15

**Comment by opi99** [comment]
This is thrown in FrontendController::inheritValue(); and it seams that an element is missing data.
But hard to tell, what is missing. Is there one element on every page?
And where does this happening in BE, as this error message is only in FE?
