### ISSUE TITLE
Update from templavoila 1.9.x - mapped "INNER" tags not in output

### ISSUE THREAD

**Issue by sascha-schieferdecker** [pluspol-interactive/templavoila#22]
First, big kudos for updating templavoila! I've begun testing it

After updating the tags mapped as "inner" vanish from the output, e.g.:

![image](https://cloud.githubusercontent.com/assets/8793359/23560358/6da3d0a0-003a-11e7-8225-57b84f048a6d.png)

becomes

![image](https://cloud.githubusercontent.com/assets/8793359/23560415/a8f4f74c-003a-11e7-9e23-1ba636e94f8d.png)

Happens with all mapped "INNER" Tags.

TYPO3 7.6.16, PHP 5.5

**Comment by opi99** [comment]
This is maybe an issue with my last commit 992064bce8c2d5089d5cecb279c72e043b8f6196
can you go one commit back and try again?
