### ISSUE TITLE
Editing of FCE in container FCE fails on third level

### ISSUE THREAD

**Issue by sascha-schieferdecker** [pluspol-interactive/templavoila#23]
To illustrate the problem:

![image](https://cloud.githubusercontent.com/assets/8793359/23560738/c65a165e-003b-11e7-8432-9889f765fdff.png)

#1437750231: The way registering a wizard in TCA has changed in 6.2 and was removed in CMS 7. Please set module[name]=module_name instead of using script=path/to/script.php in your TCA. (More information)

Editing container 2 works, problem happens on third level.

**Comment by opi99** [comment]
The error message do not have something to do with 3rd level.
You need to change your DS configuration as the error message mention it for TCA.

Didn't had time yet, to write a migration script for this.

**Comment by opi99** [comment]
With #26 I implemented now first Data Structure Update/Migration part. Maybe you can test it and take a look again to your problem, if it is resolved there.

**Comment by sascha-schieferdecker** [comment]
Thanks, the update script fixes the problem. I think this will be big help.

**Comment by opi99** [comment]
Thanks for your feedback.
