### ISSUE TITLE
Fatal error: Call to a member function getVersionSelector()

### ISSUE THREAD

**Issue by kassor** [pluspol-interactive/templavoila#27]
I get a error if i try to use the page module:

**Fatal error: Call to a member function getVersionSelector() on a non-object in /var/www/t3.profile-media.de/steute.t3.profile-media.de/typo3conf/ext/templavoila/Classes/Module/Mod1/Sidebar.php on line 272**

The method getVersionSelector() not exist in this extension.

I fixed it now with:
`if(!empty($pObj->doc)){
    $versionSelector = trim($pObj->doc->getVersionSelector($pObj->id));
}`

**Comment by opi99** [comment]
Ok, it seams your installation has the version extension enabled (but not the workspace extension)?

True, one point I didn't tested yet.
