### ISSUE TITLE
Broken update script (Extension-Manager)

### ISSUE THREAD

**Issue by snduesel** [pluspol-interactive/templavoila#4]
I get a error after the update execution in the Extension-Manager ("Execute the update script")  

Uncaught TYPO3 Exception
**Class 'tx_templavoila_staticds_wizard' not found** 
Error thrown in file
typo3_src-**7.6.14**\typo3\sysext\core\Classes\Utility\GeneralUtility.php in line 4535.

**Comment by opi99** [comment]
Yes, as this part isn't reworked yet.
But, as far as I know, you can only change DataStructure from Database to static ones. So, it isn't needed if you update.

**Comment by opi99** [comment]
This issue got fixed with following commits:

8c77e5cf77fdca3dbf3e9786f92552d9e86e269b
381e96dc4987392ad18c93f275069cbf5738aef3
4abb651e6808bffb1146d6b35ab1d1c99a45b5fb

Greetings Alex//
