### ISSUE TITLE
Broken flexform categories

### ISSUE THREAD

**Issue by snduesel** [pluspol-interactive/templavoila#5]
Hi, i have since TYPO3 7.6 a strange problem when saving categories under templavoila(plugin-flexform). The data is stored correctly in the table <mm> sys_category_record_mm <mm>. But the value is stored incorrectly in tt_content.pi_flexform and thus incorrectly displayed in my plugin ...

```
<config type="array">
	<type>select</type>
	<renderType>selectTree</renderType>
	<foreign_table>sys_category</foreign_table>
	<foreign_table_where> AND sys_category.sys_language_uid IN (-1, 0) ORDER BY sys_category.sorting ASC</foreign_table_where>
	<MM>sys_category_record_mm</MM>
	<MM_opposite_field>items</MM_opposite_field>
	<MM_match_fields>
		<tablenames>tt_content</tablenames>
		<fieldname>tx_extension_categories</fieldname>
	</MM_match_fields> 
	<size>10</size>
	<autoSizeMax>50</autoSizeMax>
	<maxitems>9999</maxitems>
	<treeConfig>
		<parentField>parent</parentField>
		<appearance>
			<expandAll>TRUE</expandAll>
			<showHeader>TRUE</showHeader>
			<maxLevels>99</maxLevels>
		</appearance>
	</treeConfig> 
</config>
```
Do you think this a problem in templavoila or a other bug?

**Comment by opi99** [comment]
Hi,
which TemplaVoilà version do you use? The one from this git repository?
It worked in TYPO3 6.2 LTS? Which TemplaVoilà version did you use there?
And where should the value stored correctly?

**Comment by snduesel** [comment]
Hi
currently in TYPO3 7.6 LTS i use this git repository. In TYPO3 7.1 i used the templavoila from TER.

**correctly**
```
#table sys_category_record_mm 

uid_local	uid_foreign	tablenames	fieldname	                 sorting	sorting_foreign
121	        1403	        tt_content	tx_extension_categories          0	        1
```
**incorrectly** Look => `<value index="vDEF">1</value>  => <value index="vDEF">121</value>`
```
#table tt_content.**pi_flexform** 

<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3FlexForms>
    <data>
        <sheet index="main">
            <language index="lDEF">
                <field index="settings.categories">
                    <value index="vDEF">1</value>
                </field>
            </language>
        </sheet>
    </data>
</T3FlexForms>
```

**Comment by opi99** [comment]
As it is an MM relation the <value index="vDEF">1</value> looks correctly and the previous value looks false.
Its like in other non flexform table configuration. Where the table field gets filled with a non zero number to show that there should be MM reference data. (Mostly it should be the count but it isn't updated by changes on the second side).

**Comment by snduesel** [comment]
Do you think this a bug in templavoila or a other bug?

**Comment by opi99** [comment]
At the moment I don't see a bug. The data seams correct.

**Comment by snduesel** [comment]
thx

**Comment by snduesel** [comment]
Hi @opi99 ,
i changed this File and then works

https://github.com/snduesel/templavoila/blob/master/Classes/Form/FormDataProvider/TcaFlexProcess.php

I think this a bug in templavoila TcaFlexProcess.php, I cant reopen this issue :|

**Comment by opi99** [comment]
Ok, will reopen and take a look on monday.
Can you add your change as push request? As you closed the one you opened.

**Comment by opi99** [comment]
Looked into the patch and ... it does to much. And some parts are moved around seams not for fixing your issue.
Also we need mostly to stay a bit in sync with the TcaFlexProcess.php from core. Else we will get more and more issues while backporting fixes from there.
Let us speak about the issue on slack, so I can try it on my system.
